--exercícios sessão 10


--QUAIS CARGOS POSSUEM MEDIA SALARIAL MAIOR QUE A MEDIA DO CARGO DO COORDENADOR DE VENDAS INTERNAS

SELECT F.Cargo, AVG(F.Salario) AS MediaCargo
FROM TB_FUNCIONARIO F
GROUP BY F.Cargo
HAVING AVG(F.Salario) > (SELECT AVG(F1.Salario) FROM TB_FUNCIONARIO F1 WHERE F1.Cargo = 'Coordenador de Vendas Internas');

--QUAL PRODUTO TEVE MAIS VENDAS NO MES 7 DE 1996

SELECT PR.Descricao, DE.Quantidade FROM TB_PRODUTO PR 
JOIN TB_DETALHE_PEDIDO DE ON PR.ProdutoId = DE.ProdutoId
where 

