

--TRAGA TUDO DA TABELA CLIENTE ONDE NA COLUNA CARGO TENHA PRIMEIRO A PALABRA REPRESENTANTE E SE TIVER ALGO A MAIS DEPOIS DO REPRESENTANTE
SELECT * FROM TB_CLIENTE
WHERE Cargo LIKE'REPRESENTANTE%'

--TRAGA TUDO DA TABELA CLIENTE ONDE NA COLUNA CARGO EU TENHA QUALQUER COISA NA FRENTE MAS O FINAL SEJA OBRIGATÓRIAMENTE PEDIDOS
SELECT * FROM TB_CLIENTE
WHERE Cargo LIKE'%PEDIDOS'


--TRAGA TUDO DA TABELA CLIENTE ONDE NA COLUNA CARGO EU TENHA QUALQUER COISA NA FRENTE, NO MEIO TENHA DE E QUALQUER COISA NO FIM. **OS ESPAÇOS CONTAM**
SELECT * FROM TB_CLIENTE
WHERE Cargo LIKE'% DE %'

--TRAGA TODOS OS SALARIOS DOS FUNCIONARIOS QUE SEJAM IGUAL(=) A 5 MIL
SELECT * FROM TB_FUNCIONARIO
WHERE Salario = 5000;

--TRAGA TODOS OS SALARIOS QUE SEJAM DIFERENTE (<>) DE 5 MIL
SELECT * FROM TB_FUNCIONARIO
WHERE Salario <> 5000;

--TRAGA TODOS OS SALARIOS QUE SEJAM MENORES (<) DO QUE 5 MIL

SELECT * FROM TB_FUNCIONARIO
WHERE Salario < 5000;

--TODOS OS SALARIOS MENORES OU IGUAL A 5 MIL (<=) 
SELECT * FROM TB_FUNCIONARIO
WHERE Salario <= 5000;

--SALARIOS ENTRE 5 MIL E 9500
SELECT * FROM TB_FUNCIONARIO
WHERE SALARIO BETWEEN 5000 AND 9500;


--países que estão em: suécia, fraça e eua
SELECT * FROM TB_ENDERECO
WHERE Pais IN('EUA','Suécia','França')

----países que não estão em: suécia, fraça e eua
SELECT * FROM TB_ENDERECO
WHERE Pais NOT IN('EUA','Suécia','França')

--PARA LIDAR COM NULO NÃO SE USA =, SE USA IS
--TRAGA ENDEREÇOS QUE A REGIÃO É NULA
SELECT * FROM TB_ENDERECO
WHERE Regiao IS NULL;

--TRAGA ENDEREÇOS QUE A REGIÃO  NÃO É NULA
SELECT * FROM TB_ENDERECO
WHERE Regiao IS NOT  NULL;

--VAMOS SELECIONAR SOMENTE CAMPOS ESPECÍFICOS E PARA UM RELATÓRIO FICAR MAIS APRENSETAVEL PODE SE USAR O IS NUL PARA MUDAR O NULL POR UMA MENSAGEM PRÉ DEFINIDA
SELECT Logradouro,Cidade,Pais, ISNULL(Regiao,'N/C') FROM TB_ENDERECO;

--UNINDO CONSULTAS DE TB FORNECEDOR E TB CLIENTE
--para union funcionar precisa ter a mesma quantidade de colunas e seu tipo tem que ser o mesmo ex: NomeCompleto(varchar), Empresa(varchar)
-- (as) - apelido para colunas
SELECT NomeCompleto AS EMPRESA, Contato, Cargo From TB_CLIENTE
UNION
SELECT Empresa,Contato,Cargo FROM TB_FORNECEDOR


--
SELECT Pais FROM TB_ENDERECO
WHERE ClienteId IS NOT NULL
INTERSECT
--EXCEPT
SELECT Pais FROM TB_ENDERECO
WHERE FuncionarioId IS NOT NULL